import os

OS_USERNAME = os.getenv('OS_USERNAME')
OS_PASSWORD = os.getenv('OS_PASSWORD')
OS_AUTH_URL = os.getenv('OS_AUTH_URL')
OS_AUTH_PLUGIN = os.getenv('OS_AUTH_PLUGIN')

OS_PROJECT_NAME = os.getenv('OS_PROJECT_NAME')
OS_PROJECT_DOMAIN_NAME = os.getenv('OS_PROJECT_DOMAIN_NAME')
OS_USER_DOMAIN_NAME = os.getenv('OS_USER_DOMAIN_NAME')

OS_INTERFACE = os.getenv('OS_INTERFACE')
OS_ENDPOINT_TYPE = os.getenv('OS_ENDPOINT_TYPE')